# Generated by Django 2.2.7 on 2019-12-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
