# Generated by Django 2.2.7 on 2019-12-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
